[project]
name = "tepkit"
version = "0.2.3"
description = """A user-friendly program for accelerating the calculation and analysis processes of \
transport, electronic, and thermoelectric properties of materials."""
authors = [
    {name = "Shu-Hao Cao", email = "csh.academic@gmail.com"}
]
readme = "README.md"
license = "GPL-3.0-only"
license-files = ["LICENSE"]
requires-python = ">=3.11"
keywords = [
    "first-principles",
    "thermoelectricity",
]
dependencies = [
    "loguru",
    "toml",
    "typer",
    "docstring_parser",
    "numpy",
    "pandas",
    "scipy",
    "matplotlib",
    "tqdm",
]

[project.urls]
Homepage = "https://github.com/TepLabCode/Tepkit"
Repository = "https://github.com/TepLabCode/Tepkit"
Issues = "https://github.com/TepLabCode/Tepkit/issues"
Changelog = "https://github.com/TepLabCode/Tepkit/blob/main/ChangeLog.md"

[project.optional-dependencies]
all = [
    "mendeleev",
    "pymatgen",
    "f90nml",
    "rich",
    "spglib",
]
doc = [
    "sphinx",
    "sphinx-autoapi",
    "sphinx-book-theme",
    "sphinxcontrib-mermaid",
    "myst-parser",
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project.scripts]
tepkit = "tepkit.cli.typer.entry:main"
